/*--------------------------------------------------------------------------
C541UEXT.H

Header file for additional C541U Register Declarations to reg540u.h.
Copyright (c) 1988-2002 Keil Elektronik GmbH and Keil Software, Inc.
All rights reserved.
--------------------------------------------------------------------------*/

#ifndef __C541UEXT_H__
#define __C541UEXT_H__

/* C541U extendet SFRs */
sfr   WDTREL = 0x86;
sfr   SSCON  = 0x93;
sfr   STB    = 0x94;
sfr   SRB    = 0x95;
sfr   SSCMOD = 0x96;
sfr   SCF    = 0xAB;
sfr   SCIEN  = 0xAC;
